routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@index');

Auth::routes();

Route::get('/admin/home', 'HomeController@index')->name('home');


//LOWONGAN
Route::prefix('/lowongan')->group(function ()
{
    Route::get('/admin', 'LowonganController@index')->name('lowongan.index');
    Route::get('/daftar-lowongan', 'LowonganController@home')->name('lowongan.home');
    Route::get('/tambah', 'LowonganController@create')->name('lowongan.tambah');
    Route::get('/detail/{id}', 'LowonganController@show')->name('lowongan.detail');
    Route::post('/tambah', 'LowonganController@store')->name('lowongan.simpan');
    Route::get('/admin/edit/{id}', 'LowonganController@edit')->name('lowongan.edit');
    Route::post('/admin/edit/{id}', 'LowonganController@update')->name('lowongan.update');
    Route::get('/admin/hapus/{id}', 'LowonganController@delete')->name('lowongan.delete');
    Route::get('/admin/hapus/{id}', 'LowonganController@destroy')->name('lowongan.hapus');
    //Kriteria
    Route::get('/admin/kriteria/{id}', 'KriteriaController@index')->name('kriteria.index');
    Route::get('/admin/kriteria/{id}/tambah', 'KriteriaController@create')->name('kriteria.tambah');
    Route::post('/admin/kriteria/tambah', 'KriteriaController@store')->name('kriteria.simpan');
    Route::get('/admin/kriteria/edit/{id}', 'KriteriaController@edit')->name('kriteria.edit');
    Route::post('/admin/kriteria/edit/{id}', 'KriteriaController@update')->name('kriteria.update');
    Route::get('/admin/kriteria/hapus/{id}', 'KriteriaController@destroy')->name('kriteria.hapus');
    //Bobot Kriteria
    Route::get('/admin/bobot_kriteria/{id}', 'BobotKriteriaController@index')->name('bobot_kriteria.index');
    Route::get('/admin/bobot_kriteria/{id}/tambah', 'BobotKriteriaController@create')->name('bobot_kriteria.tambah');
    Route::post('/admin/bobot_kriteria/tambah', 'BobotKriteriaController@store')->name('bobot_kriteria.simpan');
    Route::get('/admin/bobot_kriteria/edit/{id}', 'BobotKriteriaController@edit')->name('bobot_kriteria.edit');
    Route::post('/admin/bobot_kriteria/edit/{id}', 'BobotKriteriaController@update')->name('bobot_kriteria.update');
    Route::get('/admin/bobot_kriteria/hapus/{id}', 'BobotKriteriaController@destroy')->name('bobot_kriteria.hapus');
});


Route::prefix('/daftar_soal')->group(function ()
{
    Route::get('/admin/{id}', 'DaftarSoalController@index')->name('daftar_soal.index');
    Route::get('/admin/{id}/tambah', 'DaftarSoalController@create')->name('daftar_soal.tambah');
    Route::post('/admin/tambah', 'DaftarSoalController@store')->name('daftar_soal.simpan');
    Route::get('/admin/edit/{id}', 'DaftarSoalController@edit')->name('daftar_soal.edit');
    Route::post('/admin/edit/{id}', 'DaftarSoalController@update')->name('daftar_soal.update');
    Route::get('/admin/hapus/{id}', 'DaftarSoalController@destroy')->name('daftar_soal.hapus');
    Route::get('/admin/soal-tes/{id}', 'DaftarSoalController@home')->name('daftar_soal.home');
    
});

Route::prefix('/jadwal_tes')->group(function ()
{
    Route::get('/admin', 'JadwalTesController@index')->name('jadwal_tes.index');
    Route::get('/admin/tambah', 'JadwalTesController@create')->name('jadwal_tes.tambah');
    Route::post('/admin/tambah', 'JadwalTesController@store')->name('jadwal_tes.simpan');
    Route::get('/admin/pilih/{id}', 'JadwalTesController@pilihsoal')->name('jadwal_tes.pilihsoal');
    Route::post('/admin/pilih/{id}', 'JadwalTesController@simpansoal')->name('jadwal_tes.simpansoal');
    Route::post('/admin/hapussoal/{id}', 'JadwalTesController@hapussoal')->name('jadwal_tes.hapussoal');
    Route::get('/admin/edit/{id}', 'JadwalTesController@edit')->name('jadwal_tes.ubah');
    Route::post('/admin/edit/{id}', 'JadwalTesController@update')->name('jadwal_tes.update');
    Route::get('/admin/jadwal/hapus/{id}', 'JadwalTesController@destroy')->name('jadwal_tes.hapus');
    Route::get('/admin/jadwal', 'JadwalTesController@home')->name('soal-tes.home');

    //Jawaban
    Route::get('/hasil-tes/{id}', 'HasilTesController@index')->name('jawaban.index');
    Route::get('/jawaban/unggah/{id}', 'HasilTesController@create')->name('jawaban.unggah');
    Route::get('/jawaban/detail/{id}', 'HasilTesController@detail')->name('jawaban.detail');
    Route::post('/jawaban', 'HasilTesController@store')->name('jawaban.store');
    Route::get('/nilai-jawaban/{id}', 'HasilTesController@edit')->name('jawaban.nilai');
    Route::patch('/nilai-jawaban/{id}', 'HasilTesController@update')->name('jawaban.nilai.update');
    Route::get('/jawaban/edit/{id}', 'HasilTesController@editJawaban')->name('jawaban.edit');
    Route::patch('/jawaban/edit/{id}', 'HasilTesController@updateJawaban')->name('jawaban.update');
});

Route::prefix('/pelamar')->group(function ()
{
    Route::post('/seleksi-pelamar/{id}', 'PelamarController@update')->name('pelamar.update');
    Route::get('/admin', 'PelamarController@index')->name('pelamar.index');
    Route::get('/{id}/melamar', 'PelamarController@create')->name('pelamar.tambah');
    Route::post('/melamar', 'PelamarController@store')->name('pelamar.simpan');
    // Route::get('/edit/{id}', 'PelamarController@edit')->name('pelamar.ubah');
    Route::post('/tolak-seleksi-satu', 'PelamarController@tolakSatu')->name('pelamar.tolak.satu');
    Route::post('/tolak-seleksi-dua', 'PelamarController@tolakDua')->name('pelamar.tolak.dua');
    Route::post('/seleksi-pelamar-dua/{id}', 'PelamarController@seleksiDua')->name('pelamar.seleksi.dua');
    Route::get('/hapus/{id}', 'PelamarController@destroy')->name('pelamar.hapus');
    Route::get('/riwayat-lamaran/{id}', 'PelamarController@riwayat')->name('pelamar.riwayat');
    Route::post('/validasi-dokumen/{id}', 'PelamarController@statusDokumen')->name('pelamar.statusDokumen');
});

Route::prefix('/perhitungan')->group(function ()
{
    Route::get('/admin/seleksi-1/{id}', 'PerhitunganController@index')->name('perhitungan.index');
    Route::get('/admin/seleksi-pelamar', 'PerhitunganController@lowongan')->name('perhitungan.pelamar');
    Route::get('/admin/seleksi-detail/{id}', 'PerhitunganController@detail')->name('seleksi.detail');
    Route::get('/admin/seleksi-2/{id}', 'PerhitunganController@perhitungan2')->name('perhitungan.dua');
    Route::get('/admin/validasi/{id}', 'PerhitunganController@validation')->name('perhitungan.validasi');

    Route::get('/pdf/cv/{id}', 'PerhitunganController@pdf')->name('perhitungan.pdf');
    Route::get('/pdf/ijazah/{id}', 'PerhitunganController@pdfIjazah')->name('perhitungan.pdfIjazah');
    Route::get('/pdf/pasFoto/{id}', 'PerhitunganController@pasFoto')->name('perhitungan.pasFoto');
});

Route::prefix('/email')->group(function ()
{
    Route::get('/email/{id}', 'PelamarController@email')->name('email.index');
});


Route::prefix('/cetak')->group(function ()
{
    Route::get('/admin/cetak-seleksi-1/{id}', 'PerhitunganController@laporan1')->name('seleksi.satu');
    Route::get('/admin/cetak-seleksi-2/{id}', 'PerhitunganController@laporan2')->name('seleksi.dua');
});

// Route::get('/debug-sentry', function () {
//     throw new Exception('My first Sentry error!');
// });

app/DaftarSoal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class DaftarSoal extends Model
{
    protected $table        = 'daftar_soal';
    protected $primaryKey   = 'id_soal';
    protected $fillable     = ['soal','file_soal','bobot_soal','id_jadwal_tes', 'id_lowongan'];
    protected $hidden       = ['created_at','updated_at'];
    
    public function jadwal_tes() {
        return $this->belongsTo(JadwalTes::class,'id_jadwal_tes', 'id_jadwal_tes');
    }
    
    public function hasil_tes() {
        return $this->hasOne(HasilTes::class,'id_soal_tes', 'id_soal');
    }
    
}

app/Http/Controllers/DaftarSoalController.php
<?php

namespace App\Http\Controllers;

use App\DaftarSoal;
use App\HasilTes;
use App\JadwalTes;
use App\lowongan;
use App\Pelamar;
use RealRashid\SweetAlert\Facades\Alert;
use Illuminate\Support\Facades\File;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class DaftarSoalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($id)
    {
        if (Auth::user()->role == 'admin') {
            $jadwaltes = JadwalTes::find($id);
            $daftarsoal = DaftarSoal::where('id_jadwal_tes', $id)->get();
            $lowongan = DB::table('jadwal_tes')
                ->join('lowongan', 'lowongan.id_lowongan', '=', 'jadwal_tes.id_lowongan')
                ->where('jadwal_tes.id_jadwal_tes', $id)
                ->first();
            return view('daftar_soal.index', ['daftarsoal' => $daftarsoal, 'jadwaltes' => $jadwaltes, 'lowongan' => $lowongan]);
        } else {
            abort(404);
        }
    }

    public function home($id)
    {

        $user = Auth::user()->id;
        $pelamar = Pelamar::with('user', 'hasil_tes')->where('id_user', $user)->get();
        $pelamarGet = $pelamar[0]->id_pelamar;
        // dd($pelamarGet);
        $jadwaltes = JadwalTes::find($id);
        // dd($jadwaltes);
        $daftarsoal = DaftarSoal::where('id_jadwal_tes', $id)->withCount(['hasil_tes' => function ($q) use ($pelamarGet) {
            $q->where('id_pelamar', $pelamarGet);
        }])
            // ->where(function($q) use ($pelamarGet){
            //     $q->whereHas('hasil_tes', function($q) use ($pelamarGet) {
            //         $q->where('id_pelamar', $pelamarGet);
            //     })
            //     ->orWhereHas('hasil_tes', function($q) use ($pelamarGet) {
            //         $q->where('id_pelamar', '!=', $pelamarGet);
            //     });
            // })
            ->with(['hasil_tes' => function ($q) use ($pelamarGet) {
                $q->where('id_pelamar', $pelamarGet);
            }])
            ->get();

        if ($daftarsoal->isEmpty()) {
            $daftarsoal = $daftarsoal = DaftarSoal::where('id_jadwal_tes', $id)->withCount(['hasil_tes' => function ($q) use ($pelamarGet) {
                $q->where('id_pelamar', $pelamarGet);
            }])->get();
        }

        // ->whereHas('hasil_tes', function ($q) use ($pelamarGet) {
        //     $q->where('id_pelamar', $pelamarGet);
        // })->with(['hasil_tes' => function($q) use ($pelamarGet) {
        //     $q->where('id_pelamar', $pelamarGet);
        // }])


        // dd($daftarsoal);
        return view('daftar_soal.home', ['daftarsoal' => $daftarsoal, 'jadwaltes' => $jadwaltes, 'pelamarGet' => $pelamarGet, 'pelamar' => $pelamar]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {
        if (Auth::user()->role == 'admin') {
            $jadwaltes = JadwalTes::find($id);
            return view('daftar_soal.tambah', ['jadwaltes' => $jadwaltes]);
        } else {
            abort(404);
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make(request()->all(), [
            'soal' => 'required',
            'bobot' => "required",
            'file_soal' => "required",
        ]);

        if ($validator->fails()) {
            dd($validator->errors());
            return back()->withErrors($validator->errors());
        } else {
            Alert::success('Berhasil', 'Berhasil menambah soal');

            $daftar_soal = new DaftarSoal();
            $daftar_soal->id_jadwal_tes = $request->get('id_jadwal_tes');
            $daftar_soal->soal = $request->get('soal');
            $daftar_soal->bobot_soal = $request->get('bobot');
            if ($request->file('file_soal')) {
                $file = $request->file('file_soal');
                $filename = time() . '.' . $file->getClientOriginalExtension();
                $daftar_soal->file_soal  = $filename;
                $tujuan_upload = 'upload';
                $file->move($tujuan_upload, $filename);
            }
        }
        $daftar_soal->save();
        return redirect()->route('daftar_soal.index', ['id' => $daftar_soal->id_jadwal_tes]);
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Auth::user()->role == 'admin') {
            $daftar_soal = DaftarSoal::find($id);
            return view('daftar_soal.edit', ['daftar_soal' => $daftar_soal]);
        } else {
            abort(404);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make(request()->all(), [
            'soal' => 'required',
            'bobot' => "required",

        ]);

        if ($validator->fails()) {
            dd($validator->errors());
            return back()->withErrors($validator->errors());
        } else {
            Alert::success('Berhasil', 'Berhasil mengubah soal');

            $daftar_soal = DaftarSoal::find($id);
            $daftar_soal->soal = $request->get('soal');
            $daftar_soal->bobot_soal = $request->get('bobot');
            if ($request->file('file_soal')) {
                $file = $request->file('file_soal');
                $tujuan_upload = 'upload';
                File::delete('upload/' . $daftar_soal->file_soal);
                $filename = time() . '.' . $file->getClientOriginalExtension();
                $daftar_soal->file_soal  = $filename;
                $file->move($tujuan_upload, $filename);
            }
        }
        $daftar_soal->save();
        return redirect()->route('daftar_soal.index', ['id' => $daftar_soal->id_jadwal_tes]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $daftar_soal = DaftarSoal::find($id);
        $daftar_soal->delete();
        File::delete('upload/' . $daftar_soal->file_soal);
        return redirect()->route('daftar_soal.index', ['id' => $daftar_soal->id_jadwal_tes]);
    }
}

resources/views/daftar_soal/edit.blade.php
@extends('admin.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h2 class="float-left">Edit Soal</h2>
                        </form>
                    </div>
                    <div class="card-body">
                        <div class="row">
                        <form enctype="multipart/form-data" action="{{route('daftar_soal.update',$daftar_soal->id_soal)}}" method="POST" class="col-md-12">
                            @csrf
                            <div class="form-group">
                                <label for="soal">Soal<span class="text-danger">*</span></label>
                                <input type="text" name="soal" required class="form-control" value="{{$daftar_soal->soal}}">
                            </div>
                            <div class="form-group">
                                <label for="bobot">Bobot Soal<span class="text-danger">*</span></label>
                                <input type="number" name="bobot" required class="form-control" max="100" value="{{$daftar_soal->bobot_soal}}">
                            </div>
                            <div class="form-group">
                                <label for="file_soal">File Soal<span class="text-danger">*</span></label>
                            </div>
                            <input name="file_soal" class="form-control" type="file"/>
                            <br>
                            <div class="float-right">
                                <a href="{{ route('daftar_soal.index', ['id' => $daftar_soal->id_jadwal_tes]) }}" class="btn btn-danger">Batal</a>
                                <button type="submit" class="btn btn-success">Edit</button>
                            </div>
                        </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/daftar_soal/home.blade.php
@extends('layouts.user')

@section('content')

    {{-- @include('jawaban.jawaban') --}}

        <div class="card shadow-sm p-3 mb-5 bg-body rounded" style="margin-top: 100px;">
            <h1 class="mb-5">Tes Tulis Online</h1>
            <div class="card-body">

                {{-- <h3>
                Soal {{ $daftarsoal[0]->soal }}
            </h3>

            <br>
            <span>
                Anda bisa download soalnya disini
            </span>
            <br>
            <a href="{{ asset('/upload/' . $daftarsoal[0]->file_soal) }}" class="btn btn-primary mt-3"
                target="blank"><i class="fas fa-download"></i> &nbsp;Download File</a> --}}
                <div class="table-responsive">
                    <table class="table table-bordered" id="myTable">
                        <thead>
                            <tr>
                                <th class="text-center">No</th>
                                <th class="text-center">Soal</th>
                                <th class="text-center">File Soal</th>
                                <th class="text-center">Unggah Jawaban</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (!empty($daftarsoal))
                                @foreach ($daftarsoal as $data)
                                    <div class="modal fade" id="unggah-jawaban{{ $data->id_soal }}" tabindex="-1"
                                        aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Unggah Jawaban</h5>
                                                    <button type="button" class="close" data-dismiss="modal"
                                                        aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <form action="{{ route('jawaban.store') }}" method="POST"
                                                        enctype="multipart/form-data">

                                                        {{ csrf_field() }}

                                                        <input type="number" name="id_soal_tes"
                                                            value="{{ $data->id_soal }}" hidden>
                                                        <input type="number" name="id_pelamar" value="{{ $pelamarGet }}"
                                                            hidden>
                                                        <input type="number" name="id_lowongan"
                                                            value="{{ $pelamar[0]->id_lowongan }}" hidden>
                                                        <div class="form-group">
                                                            <span class="text-danger">Unggah jawabanmu disini, pastikan
                                                                jawaban yang kamu unggah sesuai soal!</span><br>
                                                            <input type="file" class="btn btn-warning mt-3" name="jawaban"
                                                                value="Unggah Jawaban">
                                                        </div><br>

                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary"
                                                                data-dismiss="modal">Close</button>
                                                            <button type="submit" class="btn btn-primary">Save
                                                                changes</button>
                                                        </div>
                                                        {{-- <button type="submit" class="btn btn-primary">Uggah Jawaban</button> --}}
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    @if ($data->hasil_tes_count > 0)
                                        <div class="modal fade" id="ubah-jawaban{{ $data->hasil_tes->id_hasil_tes }}"
                                            tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLabel">Unggah Jawaban
                                                        </h5>
                                                        <button type="button" class="close" data-dismiss="modal"
                                                            aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <form action="{{ route('jawaban.update', $data->hasil_tes->id_hasil_tes) }}"
                                                            method="POST" enctype="multipart/form-data">
                                                            {{ csrf_field() }}
                                                            {{ method_field('PATCH') }}

                                                            <input type="number" name="id_soal_tes"
                                                                value="{{ $data->id_soal }}" hidden>
                                                            <input type="number" name="id_pelamar"
                                                                value="{{ $pelamarGet }}" hidden>
                                                            <input type="number" name="id_lowongan"
                                                                value="{{ $pelamar[0]->id_lowongan }}" hidden>
                                                            <div class="form-group">
                                                                <span class="text-danger">Unggah jawabanmu disini,
                                                                    pastikan
                                                                    jawaban yang kamu unggah sesuai soal!</span><br>
                                                                <input type="file" class="btn btn-warning mt-3"
                                                                    name="jawaban" value="Unggah Jawaban">
                                                            </div><br>

                                                            <div class="modal-footer">
                                                                <button type="button" class="btn btn-secondary"
                                                                    data-dismiss="modal">Close</button>
                                                                <button type="submit" class="btn btn-primary">Save
                                                                    changes</button>
                                                            </div>
                                                            {{-- <button type="submit" class="btn btn-primary">Uggah Jawaban</button> --}}
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    @endif


                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $data->soal }}</td>
                                        <td align="center">
                                            <a href="/upload/{{ $data->file_soal }}" class="btn btn-primary"
                                                target="blank"><i class="fas fa-download"></i> &nbsp; Download File</a>
                                        </td>

                                        <td align="center" colspan="2">
                                            @if ($data->hasil_tes_count == 0)
                                                <a href=""
                                                    class="btn btn-success" data-toggle="modal"
                                                    data-target="#unggah-jawaban{{ $data->id_soal }}">Unggah Jawaban</a>
                                            @else
                                                <a href="{{ asset('storage/file/jawaban/' . $data->hasil_tes->jawaban) }}"
                                                    class="btn btn-success btn-md" target="blank">Unduh Jawaban</a>
                                                    <br> <br>
                                                <a href="" class="btn btn-danger btn-md" data-toggle="modal"
                                                    data-target="#ubah-jawaban{{ $data->hasil_tes->id_hasil_tes }}" >Ubah Jawaban</a>
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach
                            @else
                                <tr>
                                    <td colspan="5" class="text-center">Data tidak ditemukan</td>
                                </tr>
                            @endif
                        </tbody>
                    </table>

                    {{-- <form action="{{ route('jawaban.store') }}" method="POST" enctype="multipart/form-data">

                {{ csrf_field() }}


                <input type="number" name="id_soal_tes" value="{{ $daftarsoal[0]->id_soal }}" hidden>
                <input type="number" name="id_pelamar" value="{{ $pelamarGet }}" hidden>
                <input type="number" name="id_lowongan" value="{{ $pelamar[0]->id_lowongan }}" hidden>
                <div class="form-group">
                    <h3>Unggah Jawaban</h3><br>
                    <span>Jika sudah menyelesaikan soal unggah jawabanmu disini</span><br>
                    <input type="file" class="btn btn-success mt-3" name="jawaban" value="Unggah Jawaban">
                </div><br>

                <button type="submit" class="btn btn-primary">Uggah Jawaban</button>
            </form> --}}



                </div>
            </div>
        </div>


    @endsection

resources/views/daftar_soal/tambah.blade.php
@extends('admin.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h2 class="float-left">Tambah Soal</h2>
                    </form>
                </div>

                <div class="card-body">
                    <div class="row">
                        <form enctype="multipart/form-data" action="{{route('daftar_soal.simpan')}}" method="POST" class="col-md-12">
                            @csrf
                            <div class="form-group">
                                    <input type="text" name="id_jadwal_tes" class="form-control" value="{{$jadwaltes->id_jadwal_tes}}" hidden>
                                </div>
                            <div class="form-group">
                                <label for="soal">Soal<span class="text-danger">*</span></label>
                                <input type="text" name="soal" required class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="bobot">Bobot Soal<span class="text-danger">*</span></label>
                                <input type="number" name="bobot" required class="form-control" max="100">
                            </div>
                            <div class="form-group">
                                <label for="file_soal">File Soal<span class="text-danger">*</span></label>
                            </div>
                            <input name="file_soal" class="form-control" type="file" required />
                            <br>
                            <div class="float-right">
                                <a href="{{ route('daftar_soal.index', ['id' => $jadwaltes->id_jadwal_tes]) }}" class="btn btn-danger">Batal</a>
                                <button type="submit" class="btn btn-success">Tambah</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection